{
 "title": "Wireguard_New",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interface",
    "query": {
     "query": "label_values(wireguard_peers_total{dc=~\"$dc\", hostname=~\"$hostname\"}, interface)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Peers total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "wireguard_peers_total{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total bytes RX",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wireguard_bytes_total{direction=\"rx\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total bytes TX",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wireguard_bytes_total{direction=\"tx\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RX/TX rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(irate(wireguard_bytes_total{}[5m])) by (direction)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peers information",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(wireguard_peer_bytes_total{}) by (hostname, peer, interface) * on(hostname, peer, interface) group_left(name) wireguard_meta ",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(wireguard_peer_bytes_total{direction=\"rx\"}) by (hostname, peer)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(wireguard_peer_bytes_total{direction=\"tx\"}) by (hostname, peer)",
     "legendFormat": "__auto"
    },
    {
     "expr": "wireguard_duration_since_latest_handshake{} / 1000",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}